app:
  output_folder: ./output
llm:
  temperature: 1.1
story:
  max_words: 200
telegram:
  bot_token: ''
  chat_id: ''
video:
  bgm: ''
  font_color: '#ffffff'
  font_path: res/fonts/AndikaNewBasic-R.ttf
  font_size: 60
  language: English
  stroke_color: '#000000'
  stroke_width: 4
  subtitle_position: 41
  voice_rate: 1.05
