
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "uvicorn app.apis.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes: 
      - ./:/daily-story-short-generator
    restart: always

  ui:
    build:
      context: .
    ports:
      - "8501:8501"
    command: "streamlit run app/ui/main.py"
    volumes: 
      - ./:/daily-story-short-generator
    restart: always

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - api
      - ui

  celery:
    container_name: celery
    build: .
    command: celery -A app.workers.celery_worker.app worker -B --loglevel=info --concurrency=4
    volumes:
      - .:/daily-story-short-generator
    depends_on:
      - api
      - ui
      - redis